import type { Metadata } from "next";
import { Sofia_Sans as SF } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const Sofia = SF({weight: "400", subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Sofia.className}>
        <Header />
        {children}</body>
    </html>
  );
}
